import {
  Wilaya,
  Institution,
  Faculty,
  Specialty,
  AcademicYear,
  ModuleItem,
  ExamItem,
  User,
  AmbassadorProfile,
  Post,
  Locale,
  TeacherProfile,
  DawaaraPack,
  DawaaraModule,
  ModuleResource,
  TeacherRosterStudent,
  AmbassadorSaleRecord,
  PackEnrollment,
  TeacherLiveSession,
} from '@/types';

export const WILAYAS: Wilaya[] = [
  { code: 1, nameAr: 'أدرار', nameFr: 'Adrar', nameEn: 'Adrar', region: 'SOUTH' },
  { code: 2, nameAr: 'الشلف', nameFr: 'Chlef', nameEn: 'Chlef', region: 'WEST' },
  { code: 5, nameAr: 'باتنة', nameFr: 'Batna', nameEn: 'Batna', region: 'EAST' },
  { code: 6, nameAr: 'بجاية', nameFr: 'Béjaïa', nameEn: 'Bejaia', region: 'CENTER' },
  { code: 7, nameAr: 'بسكرة', nameFr: 'Biskra', nameEn: 'Biskra', region: 'SOUTH' },
  { code: 9, nameAr: 'البليدة', nameFr: 'Blida', nameEn: 'Blida', region: 'CENTER' },
  { code: 13, nameAr: 'تلمسان', nameFr: 'Tlemcen', nameEn: 'Tlemcen', region: 'WEST' },
  { code: 15, nameAr: 'تيزي وزو', nameFr: 'Tizi Ouzou', nameEn: 'Tizi Ouzou', region: 'CENTER' },
  { code: 16, nameAr: 'الجزائر العاصمة', nameFr: 'Alger', nameEn: 'Algiers', region: 'CENTER' },
  { code: 19, nameAr: 'سطيف', nameFr: 'Sétif', nameEn: 'Setif', region: 'EAST' },
  { code: 23, nameAr: 'عنابة', nameFr: 'Annaba', nameEn: 'Annaba', region: 'EAST' },
  { code: 25, nameAr: 'قسنطينة', nameFr: 'Constantine', nameEn: 'Constantine', region: 'EAST' },
  { code: 27, nameAr: 'مستغانم', nameFr: 'Mostaganem', nameEn: 'Mostaganem', region: 'WEST' },
  { code: 30, nameAr: 'ورقلة', nameFr: 'Ouargla', nameEn: 'Ouargla', region: 'SOUTH' },
  { code: 31, nameAr: 'وهران', nameFr: 'Oran', nameEn: 'Oran', region: 'WEST' },
  { code: 35, nameAr: 'بومرداس', nameFr: 'Boumerdès', nameEn: 'Boumerdes', region: 'CENTER' },
  { code: 47, nameAr: 'غرداية', nameFr: 'Ghardaïa', nameEn: 'Ghardaia', region: 'SOUTH' },
];

export const INSTITUTIONS: Institution[] = [
  // Universities
  {
    id: 'inst-usthb',
    nameAr: 'جامعة العلوم والتكنولوجيا هواري بومدين (USTHB - باب الزوار)',
    nameFr: 'Université des Sciences et de la Technologie Houari Boumediene (USTHB)',
    type: 'UNIVERSITY',
    wilayaCode: 16,
    logoUrl: '/logos/usthb.png',
  },
  {
    id: 'inst-alger1',
    nameAr: 'جامعة الجزائر 1 - بن يوسف بن خدة (كلية الطب والعلوم)',
    nameFr: "Université d'Alger 1 - Benyoucef Benkhedda (Médecine & Sciences)",
    type: 'UNIVERSITY',
    wilayaCode: 16,
    logoUrl: '/logos/alger1.png',
  },
  {
    id: 'inst-usto',
    nameAr: 'جامعة العلوم والتكنولوجيا وهران - محمد بوضياف (USTO-MB)',
    nameFr: 'Université des Sciences et de la Technologie d\'Oran - Mohamed Boudiaf (USTO)',
    type: 'UNIVERSITY',
    wilayaCode: 31,
    logoUrl: '/logos/usto.png',
  },
  {
    id: 'inst-mentouri',
    nameAr: 'جامعة الإخوة منتوري - قسنطينة 1 (Mentouri)',
    nameFr: 'Université Frères Mentouri - Constantine 1',
    type: 'UNIVERSITY',
    wilayaCode: 25,
    logoUrl: '/logos/mentouri.png',
  },
  {
    id: 'inst-setif1',
    nameAr: 'جامعة فرحات عباس - سطيف 1',
    nameFr: 'Université Ferhat Abbas - Sétif 1',
    type: 'UNIVERSITY',
    wilayaCode: 19,
    logoUrl: '/logos/setif1.png',
  },
  {
    id: 'inst-annaba',
    nameAr: 'جامعة باجي مختار - عنابة (UBMA)',
    nameFr: 'Université Badji Mokhtar - Annaba',
    type: 'UNIVERSITY',
    wilayaCode: 23,
    logoUrl: '/logos/annaba.png',
  },
  {
    id: 'inst-tlemcen',
    nameAr: 'جامعة أبو بكر بلقايد - تلمسان',
    nameFr: 'Université Abou Bekr Belkaïd - Tlemcen',
    type: 'UNIVERSITY',
    wilayaCode: 13,
    logoUrl: '/logos/tlemcen.png',
  },
  {
    id: 'inst-tizi',
    nameAr: 'جامعة مولود معمري - تيزي وزو (UMMTO)',
    nameFr: 'Université Mouloud Mammeri - Tizi Ouzou',
    type: 'UNIVERSITY',
    wilayaCode: 15,
    logoUrl: '/logos/ummto.png',
  },
  // High School General Track (BAC National)
  {
    id: 'inst-bac-national',
    nameAr: 'التعليم الثانوي الوطني - شهادة البكالوريا (BAC)',
    nameFr: 'Enseignement Secondaire National - Baccalauréat Algérien (BAC)',
    type: 'HIGH_SCHOOL',
    wilayaCode: 16,
  },
];

export const FACULTIES: Faculty[] = [
  // USTHB
  { id: 'fac-usthb-info', nameAr: 'كلية الإعلام الآلي', nameFr: "Faculté d'Informatique", institutionId: 'inst-usthb' },
  { id: 'fac-usthb-st', nameAr: 'كلية العلوم والتكنولوجيا والهندسة', nameFr: 'Faculté des Sciences et Technologies (ST)', institutionId: 'inst-usthb' },
  { id: 'fac-usthb-sm', nameAr: 'كلية علوم المادة (فيزياء وكيمياء)', nameFr: 'Faculté des Sciences de la Matière (SM)', institutionId: 'inst-usthb' },
  // Alger 1 (Medical)
  { id: 'fac-med-alger', nameAr: 'كلية الطب والصيدلة وطب الأسنان', nameFr: 'Faculté de Médecine et Pharmacie', institutionId: 'inst-alger1' },
  // USTO
  { id: 'fac-usto-info', nameAr: 'كلية الرياضيات والإعلام الآلي', nameFr: 'Faculté de Mathématiques et Informatique', institutionId: 'inst-usto' },
  // Mentouri Constantine
  { id: 'fac-mentouri-sciences', nameAr: 'كلية العلوم الدقيقة والإعلام الآلي', nameFr: 'Faculté des Sciences Exactes et Informatique', institutionId: 'inst-mentouri' },
  // BAC National
  { id: 'fac-bac-branches', nameAr: 'شعب البكالوريا الوطنية', nameFr: 'Filières Officielles du Baccalauréat', institutionId: 'inst-bac-national' },
];

export const SPECIALTIES: Specialty[] = [
  // University Info
  { id: 'spec-mi-tc', nameAr: 'جذع مشترك رياضيات وإعلام آلي (MI)', nameFr: 'Tronc Commun Mathématiques & Informatique (MI)', trackType: 'UNIVERSITY_LMD', facultyId: 'fac-usthb-info' },
  { id: 'spec-info-l2l3', nameAr: 'إعلام آلي عام (ISIL / SI)', nameFr: 'Licence Informatique Générale (ISIL / SI)', trackType: 'UNIVERSITY_LMD', facultyId: 'fac-usthb-info' },
  // University ST
  { id: 'spec-st-tc', nameAr: 'جذع مشترك علوم وتكنولوجيا (ST)', nameFr: 'Tronc Commun Sciences & Technologies (ST)', trackType: 'UNIVERSITY_LMD', facultyId: 'fac-usthb-st' },
  { id: 'spec-genie-civil', nameAr: 'هندسة مدنية وبناء', nameFr: 'Génie Civil & Construction', trackType: 'UNIVERSITY_LMD', facultyId: 'fac-usthb-st' },
  // Medical
  { id: 'spec-medecine', nameAr: 'دكتور في الطب البشري', nameFr: 'Doctorat en Médecine Générale', trackType: 'MEDICAL', facultyId: 'fac-med-alger' },
  { id: 'spec-pharmacie', nameAr: 'دكتور في الصيدلة', nameFr: 'Doctorat en Pharmacie', trackType: 'MEDICAL', facultyId: 'fac-med-alger' },
  // USTO Info
  { id: 'spec-usto-mi', nameAr: 'جذع مشترك MI - وهران', nameFr: 'Tronc Commun MI - USTO Oran', trackType: 'UNIVERSITY_LMD', facultyId: 'fac-usto-info' },
  // Constantine Info
  { id: 'spec-mentouri-mi', nameAr: 'جذع مشترك MI - قسنطينة', nameFr: 'Tronc Commun MI - Constantine', trackType: 'UNIVERSITY_LMD', facultyId: 'fac-mentouri-sciences' },
  // BAC Streams
  { id: 'spec-bac-scientifique', nameAr: 'شعبة علوم تجريبية (3AS)', nameFr: 'Sciences Expérimentales (3AS BAC)', trackType: 'BAC', facultyId: 'fac-bac-branches' },
  { id: 'spec-bac-math', nameAr: 'شعبة رياضيات (3AS Math)', nameFr: 'Mathématiques (3AS BAC)', trackType: 'BAC', facultyId: 'fac-bac-branches' },
  { id: 'spec-bac-technique', nameAr: 'شعبة تقني رياضي (هندسة)', nameFr: 'Technique Mathématique (3AS BAC)', trackType: 'BAC', facultyId: 'fac-bac-branches' },
  { id: 'spec-bac-gestion', nameAr: 'شعبة تسيير واقتصاد', nameFr: 'Gestion et Économie (3AS BAC)', trackType: 'BAC', facultyId: 'fac-bac-branches' },
];

export const ACADEMIC_YEARS: AcademicYear[] = [
  // MI TC (L1)
  { id: 'year-mi-s1', nameAr: 'السنة الأولى L1 - السداسي الأول (S1)', nameFr: 'Première Année L1 - Semestre 1 (S1)', semester: 'S1', specialtyId: 'spec-mi-tc' },
  { id: 'year-mi-s2', nameAr: 'السنة الأولى L1 - السداسي الثاني (S2)', nameFr: 'Première Année L1 - Semestre 2 (S2)', semester: 'S2', specialtyId: 'spec-mi-tc' },
  // Info L2
  { id: 'year-info-l2-s3', nameAr: 'السنة الثانية L2 - السداسي الثالث (S3)', nameFr: 'Deuxième Année L2 - Semestre 3 (S3)', semester: 'S3', specialtyId: 'spec-info-l2l3' },
  { id: 'year-info-l2-s4', nameAr: 'السنة الثانية L2 - السداسي الرابع (S4)', nameFr: 'Deuxième Année L2 - Semestre 4 (S4)', semester: 'S4', specialtyId: 'spec-info-l2l3' },
  // ST TC (L1)
  { id: 'year-st-s1', nameAr: 'السنة الأولى L1 ST - السداسي الأول (S1)', nameFr: 'Première Année ST - Semestre 1 (S1)', semester: 'S1', specialtyId: 'spec-st-tc' },
  // Medecine 1ere annee
  { id: 'year-med-1', nameAr: 'السنة الأولى طب بشري (1ère Année)', nameFr: '1ère Année Médecine (Cycle Préclinique)', semester: 'Annual', specialtyId: 'spec-medecine' },
  // BAC Scientifique
  { id: 'year-bac-sci-full', nameAr: 'السنة الثالثة ثانوي (3AS - البكالوريا)', nameFr: '3ème Année Secondaire - Session BAC', semester: 'Annual', specialtyId: 'spec-bac-scientifique' },
  // BAC Math
  { id: 'year-bac-math-full', nameAr: 'السنة الثالثة ثانوي رياضيات (3AS Math)', nameFr: '3ème Année Mathématiques - Session BAC', semester: 'Annual', specialtyId: 'spec-bac-math' },
];

export const MODULES: ModuleItem[] = [
  // L1 MI S1
  { id: 'mod-analyse1', nameAr: 'تحليل رياضي 1 (Analyse 1)', nameFr: 'Analyse Mathématique 1', code: 'MATH101', coefficient: 4, academicYearId: 'year-mi-s1', examsCount: 8 },
  { id: 'mod-algebre1', nameAr: 'جبر 1 (Algèbre 1)', nameFr: 'Algèbre Linéaire 1', code: 'MATH102', coefficient: 3, academicYearId: 'year-mi-s1', examsCount: 6 },
  { id: 'mod-algo1', nameAr: 'خوارزميات وهياكل بيانات 1 (ALSD 1)', nameFr: 'Algorithmique & Structures de Données 1', code: 'INFO101', coefficient: 4, academicYearId: 'year-mi-s1', examsCount: 9 },
  { id: 'mod-arch1', nameAr: 'بنية الآلة 1 (Structure Machine 1)', nameFr: 'Structure Machine 1 (Archi)', code: 'INFO102', coefficient: 3, academicYearId: 'year-mi-s1', examsCount: 5 },
  { id: 'mod-phys1', nameAr: 'فيزياء 1 - ميكانيك النقطة', nameFr: 'Physique 1 (Mécanique du Point)', code: 'PHYS101', coefficient: 2, academicYearId: 'year-mi-s1', examsCount: 4 },
  
  // L2 Info S3
  { id: 'mod-algo3', nameAr: 'خوارزميات متقدمة (ALSD 3)', nameFr: 'Algorithmique Avancée & Arbres', code: 'INFO201', coefficient: 4, academicYearId: 'year-info-l2-s3', examsCount: 7 },
  { id: 'mod-poo', nameAr: 'البرمجة كائنية التوجه (POO Java/C++)', nameFr: 'Programmation Orientée Objet (POO)', code: 'INFO202', coefficient: 3, academicYearId: 'year-info-l2-s3', examsCount: 6 },
  { id: 'mod-bd', nameAr: 'قواعد البيانات (BDD SQL)', nameFr: 'Bases de Données Relationnelles', code: 'INFO203', coefficient: 3, academicYearId: 'year-info-l2-s3', examsCount: 8 },
  { id: 'mod-si', nameAr: 'أنظمة المعلومات (Systèmes d\'Information)', nameFr: 'Systèmes d\'Information & Modélisation', code: 'INFO204', coefficient: 2, academicYearId: 'year-info-l2-s3', examsCount: 4 },

  // L1 ST S1
  { id: 'mod-st-math1', nameAr: 'رياضيات 1 (Mathématiques 1)', nameFr: 'Mathématiques Appliquées 1 (ST)', code: 'ST-M1', coefficient: 3, academicYearId: 'year-st-s1', examsCount: 5 },
  { id: 'mod-st-phys1', nameAr: 'فيزياء 1 (Physique 1)', nameFr: 'Physique 1 (Mécanique Générale)', code: 'ST-P1', coefficient: 3, academicYearId: 'year-st-s1', examsCount: 5 },
  { id: 'mod-st-chim1', nameAr: 'كيمياء 1 - بنية المادة', nameFr: 'Chimie 1 (Structure de la Matière)', code: 'ST-C1', coefficient: 3, academicYearId: 'year-st-s1', examsCount: 6 },

  // Medecine 1ere
  { id: 'mod-med-anat', nameAr: 'تشريح عام وتطبيقي (Anatomie)', nameFr: 'Anatomie Générale & Topographique', code: 'MED-ANAT', coefficient: 4, academicYearId: 'year-med-1', examsCount: 12 },
  { id: 'mod-med-histo', nameAr: 'علم الأنسجة والأجنة (Histologie)', nameFr: 'Histologie & Embryologie Médicale', code: 'MED-HIST', coefficient: 3, academicYearId: 'year-med-1', examsCount: 8 },
  { id: 'mod-med-physio', nameAr: 'علم وظائف الأعضاء (Physiologie)', nameFr: 'Physiologie Générale & Systémique', code: 'MED-PHYS', coefficient: 3, academicYearId: 'year-med-1', examsCount: 9 },

  // BAC Scientifique
  { id: 'mod-bac-math', nameAr: 'الرياضيات - بكالوريا علوم تجريبية', nameFr: 'Mathématiques BAC Sciences Exp.', code: 'BAC-MATH', coefficient: 5, academicYearId: 'year-bac-sci-full', examsCount: 15 },
  { id: 'mod-bac-sciences', nameAr: 'علوم الطبيعة والحياة - بكالوريا', nameFr: 'Sciences de la Nature & de la Vie', code: 'BAC-SNV', coefficient: 6, academicYearId: 'year-bac-sci-full', examsCount: 18 },
  { id: 'mod-bac-physique', nameAr: 'العلوم الفيزيائية - بكالوريا', nameFr: 'Physique-Chimie BAC', code: 'BAC-PHYS', coefficient: 5, academicYearId: 'year-bac-sci-full', examsCount: 16 },
  { id: 'mod-bac-arabe', nameAr: 'اللغة العربية وآدابها - بكالوريا', nameFr: 'Langue & Littérature Arabes BAC', code: 'BAC-AR', coefficient: 2, academicYearId: 'year-bac-sci-full', examsCount: 10 },
];

export const EXAMS: ExamItem[] = [
  // Analyse 1 Exams
  {
    id: 'exam-ana-2024-final',
    title: 'Examen Final Semestriel - Analyse 1 (Session Normale)',
    year: 2024,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/usthb_analyse1_2024_final.pdf',
    solutionUrl: '/exams/usthb_analyse1_2024_final_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 1420,
    moduleId: 'mod-analyse1',
    moduleName: 'Analyse 1',
    authorName: 'Dr. Brahimi & Équipe USTHB',
    createdAt: '2024-02-15',
  },
  {
    id: 'exam-ana-2024-emd1',
    title: 'EMD 1 / Interrogation Écrite - Suites et Fonctions',
    year: 2024,
    termType: 'MIDTERM_EMD',
    fileUrl: '/exams/usthb_analyse1_2024_emd1.pdf',
    solutionUrl: '/exams/usthb_analyse1_2024_emd1_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 980,
    moduleId: 'mod-analyse1',
    moduleName: 'Analyse 1',
    authorName: 'Ambassadeur USTHB',
    createdAt: '2023-11-20',
  },
  {
    id: 'exam-ana-2023-rat',
    title: 'Examen de Rattrapage - Analyse 1 (Session 2023)',
    year: 2023,
    termType: 'RATTRAPAGE',
    fileUrl: '/exams/usthb_analyse1_2023_rat.pdf',
    solutionUrl: '/exams/usthb_analyse1_2023_rat_corrige.pdf',
    isFreeSample: false, // Paid only
    downloadsCount: 620,
    moduleId: 'mod-analyse1',
    moduleName: 'Analyse 1',
    authorName: 'Dr. Brahimi',
    createdAt: '2023-06-18',
  },
  {
    id: 'exam-ana-2022-final',
    title: 'Sujet d\'Examen de Synthèse + Corrigé Barème Détaillé',
    year: 2022,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/usthb_analyse1_2022_final.pdf',
    solutionUrl: '/exams/usthb_analyse1_2022_final_corrige.pdf',
    isFreeSample: false, // Paid only
    downloadsCount: 1150,
    moduleId: 'mod-analyse1',
    moduleName: 'Analyse 1',
    authorName: 'Équipe Pédagogique DZ Prime',
    createdAt: '2022-02-10',
  },

  // Algo 1 Exams
  {
    id: 'exam-algo-2024-final',
    title: 'Examen Final ALSD 1 (Pointeurs, Récursivité, Tableaux)',
    year: 2024,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/usthb_algo1_2024_final.pdf',
    solutionUrl: '/exams/usthb_algo1_2024_final_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 2310,
    moduleId: 'mod-algo1',
    moduleName: 'Algorithmique 1',
    authorName: 'Pr. Meziane',
    createdAt: '2024-02-18',
  },
  {
    id: 'exam-algo-2024-tp',
    title: 'Test Pratique Machine C/Pascal + Algorithmes Tri',
    year: 2024,
    termType: 'MIDTERM_EMD',
    fileUrl: '/exams/usthb_algo1_2024_tp.pdf',
    solutionUrl: '/exams/usthb_algo1_2024_tp_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 1540,
    moduleId: 'mod-algo1',
    moduleName: 'Algorithmique 1',
    authorName: 'Ambassadeur Informatique',
    createdAt: '2024-01-10',
  },
  {
    id: 'exam-algo-2023-full',
    title: 'Archive Complète 10 Ans d\'Examens Corrigés ALSD',
    year: 2023,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/usthb_algo1_archive_gold.pdf',
    solutionUrl: '/exams/usthb_algo1_archive_gold_solutions.pdf',
    isFreeSample: false, // Paid only
    downloadsCount: 3890,
    moduleId: 'mod-algo1',
    moduleName: 'Algorithmique 1',
    authorName: 'Club Informatique DZ Prime',
    createdAt: '2023-09-01',
  },

  // BAC Math Exams
  {
    id: 'exam-bac-math-2024',
    title: 'BAC Blanc National 2024 - Mathématiques (Sujet + Corrigé Barème)',
    year: 2024,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/bac_math_2024_blanc.pdf',
    solutionUrl: '/exams/bac_math_2024_blanc_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 5400,
    moduleId: 'mod-bac-math',
    moduleName: 'Mathématiques BAC',
    authorName: 'Collectif National des Enseignants',
    createdAt: '2024-05-15',
  },
  {
    id: 'exam-bac-math-2023-sujet1',
    title: 'BAC Officiel 2023 - Sujet 1 (Fonctions & Nombres Complexes)',
    year: 2023,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/bac_math_2023_officiel.pdf',
    solutionUrl: '/exams/bac_math_2023_officiel_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 8200,
    moduleId: 'mod-bac-math',
    moduleName: 'Mathématiques BAC',
    authorName: 'ONEC Algérie',
    createdAt: '2023-06-25',
  },
  {
    id: 'exam-bac-math-gold-pack',
    title: 'Pack Gold Excellence: 50 Sujets Types BAC Résolus Pas à Pas',
    year: 2024,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/bac_math_gold_pack_2024.pdf',
    solutionUrl: '/exams/bac_math_gold_pack_2024_corrige.pdf',
    isFreeSample: false, // Paid only
    downloadsCount: 4200,
    moduleId: 'mod-bac-math',
    moduleName: 'Mathématiques BAC',
    authorName: 'Élite DZ Prime',
    createdAt: '2024-03-01',
  },

  // Anatomie Medecine
  {
    id: 'exam-med-anat-2024',
    title: 'QCM & Cas Cliniques d\'Anatomie - Membre Supérieur & Thorax',
    year: 2024,
    termType: 'MIDTERM_EMD',
    fileUrl: '/exams/alger1_anat_2024_emd1.pdf',
    solutionUrl: '/exams/alger1_anat_2024_emd1_corrige.pdf',
    isFreeSample: true,
    downloadsCount: 1890,
    moduleId: 'mod-med-anat',
    moduleName: 'Anatomie',
    authorName: 'Faculté de Médecine Ben Aknoun',
    createdAt: '2024-01-22',
  },
  {
    id: 'exam-med-anat-gold',
    title: 'Annales Officielles Corrigées de Médecine Alger 1 (2015-2024)',
    year: 2024,
    termType: 'FINAL_SEMESTRIAL',
    fileUrl: '/exams/alger1_med_annales_gold.pdf',
    solutionUrl: '/exams/alger1_med_annales_gold_corrige.pdf',
    isFreeSample: false, // Paid only
    downloadsCount: 2980,
    moduleId: 'mod-med-anat',
    moduleName: 'Anatomie',
    authorName: 'Pôle Médical DZ Prime',
    createdAt: '2024-02-01',
  }
];

export const DEMO_USERS: User[] = [
  {
    id: 'user-admin',
    email: 'admin@dzprime.academy',
    name: 'Riad Benmhidi',
    role: 'OWNER',
    phone: '+213 555 12 34 56',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institutionId: 'inst-usthb',
    institutionName: 'USTHB Bab Ezzouar',
    studentCardId: 'DZ-OWN-16-0001',
    isVerified: true,
    createdAt: '2023-01-01',
  },
  {
    id: 'user-coordinator',
    email: 'coordinator@dzprime.academy',
    name: 'Karim Benaissa',
    role: 'AGENT_TECHNIQUE',
    phone: '+213 560 99 88 77',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institutionId: 'inst-usthb',
    institutionName: 'Coordination Pédagogique & Technique',
    studentCardId: 'DZ-TEC-16-0088',
    isVerified: true,
    createdAt: '2023-03-01',
  },
  {
    id: 'user-ambassador',
    email: 'ambassador.alger@dzprime.academy',
    name: 'Alaa Eddine',
    role: 'AMBASSADOR',
    phone: '+213 661 23 45 67',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institutionId: 'inst-usthb',
    institutionName: 'Université USTHB',
    specialty: 'Informatique (MI L2)',
    academicYear: 'Master 1',
    studentCardId: 'DZ-AMB-16-0789',
    isVerified: true,
    createdAt: '2023-09-10',
  },
  {
    id: 'user-teacher',
    email: 'teacher.math@dzprime.academy',
    name: 'Pr. Abdelrahim Kadri',
    role: 'TEACHER',
    phone: '+213 770 98 76 54',
    wilayaCode: 19,
    wilayaName: 'Sétif',
    institutionId: 'inst-setif1',
    institutionName: 'Université Ferhat Abbas Sétif 1',
    studentCardId: 'DZ-TCH-19-0142',
    isVerified: true,
    createdAt: '2023-05-12',
  },
  {
    id: 'user-student-bac',
    email: 'anis.bac@dzprime.academy',
    name: 'Anis Benali',
    role: 'STUDENT_PAID',
    phone: '+213 550 11 22 33',
    wilayaCode: 16,
    wilayaName: 'الجزائر العاصمة',
    institutionId: 'inst-lycee-alger',
    institutionName: 'ثانوية فرانز فانون - الجزائر',
    specialty: '3AS Sciences Expérimentales (BAC 2026)',
    academicYear: '3ème Année Secondaire',
    studentCardId: 'DZ-BAC-16-9921',
    isVerified: true,
    createdAt: '2024-01-10',
  },
  {
    id: 'user-student-gold',
    email: 'taylor.lmd@dzprime.academy',
    name: 'Taylor Belalem',
    role: 'STUDENT_PAID',
    phone: '+213 550 44 33 22',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institutionId: 'inst-usthb',
    institutionName: 'Université USTHB Bab Ezzouar',
    specialty: 'L2 Informatique & Ingénierie Logicielle',
    academicYear: 'L2 S3',
    studentCardId: 'DZ-GLD-16-8841',
    isVerified: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'user-student-med',
    email: 'sara.med@dzprime.academy',
    name: 'Dr. Sara Merabtine',
    role: 'STUDENT_PAID',
    phone: '+213 661 88 99 00',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institutionId: 'inst-alger1',
    institutionName: 'Faculté de Médecine d\'Alger - Ben Aknoun',
    specialty: 'Sciences Médicales & QCM Résidanat',
    academicYear: 'Tronc Commun Médecine & Résidanat',
    studentCardId: 'DZ-MED-16-7734',
    isVerified: true,
    createdAt: '2024-01-20',
  },
  {
    id: 'user-student-free',
    email: 'student.free@dzprime.academy',
    name: 'Yacine Belalem',
    role: 'STUDENT_FREE',
    phone: '+213 699 11 22 33',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institutionId: 'inst-usthb',
    institutionName: 'Université USTHB',
    specialty: 'Tronc Commun MI L1',
    academicYear: 'L1 S1',
    studentCardId: 'DZ-STU-16-4412',
    isVerified: false,
    createdAt: '2024-02-01',
  },
];

export const TEACHERS: TeacherProfile[] = [
  {
    id: 'tch-kadri',
    name: 'Pr. Abdelrahim Kadri',
    titleAr: 'أستاذ مبرز في الرياضيات والتحليل الرياضي',
    titleFr: 'Professeur Agrégé en Mathématiques & Analyse',
    specialty: 'Mathématiques & Analyse Numérique',
    avatar: '👨‍🏫',
    experienceYears: 16,
    institution: 'جامعة فرحات عباس - سطيف 1',
    bioAr: 'خبرة أكثر من 16 سنة في تحضير طلبة البكالوريا للأولمبياد والامتياز وحل المسائل المعقدة في الدوال والمتتاليات والاحتمالات.',
    bioFr: 'Plus de 16 ans d\'expérience dans la préparation au BAC d\'Excellence et la maîtrise de l\'Analyse mathématique.',
    assignedModuleIds: ['mod-bac-math', 'mod-lmd-analyse'],
  },
  {
    id: 'tch-mansouri',
    name: 'Dr. Salim Mansouri',
    titleAr: 'دكتور في الفيزياء التجريبية والكيمياء الحركية',
    titleFr: 'Docteur en Sciences Physiques & Chimie Cinétique',
    specialty: 'Physique-Chimie & Électromagnétisme',
    avatar: '🔬',
    experienceYears: 14,
    institution: 'جامعة العلوم والتكنولوجيا USTHB',
    bioAr: 'مؤلف سلاسل الامتياز في الفيزياء. متخصص في تبسيط الظواهر الميكانيكية والكهربائية والأحماض والأسس لطلبة البكالوريا والجامعة.',
    bioFr: 'Auteur d\'ouvrages de référence en Physique-Chimie pour le BAC et le Tronc Commun.',
    assignedModuleIds: ['mod-bac-phys', 'mod-lmd-archi'],
  },
  {
    id: 'tch-amrani',
    name: 'Mme. Leila Amrani',
    titleAr: 'أستاذة رئيسية في علوم الطبيعة والحياة والمنهجية العلمية',
    titleFr: 'Professeure Principale en Sciences Naturelles & SVT',
    specialty: 'Sciences Naturelles & Génétique',
    avatar: '👩‍🔬',
    experienceYears: 18,
    institution: 'ثانوية الرياضيات بالقبة / جامعة الجزائر 1',
    bioAr: 'خبيرة في شبكات تنقيط البكالوريا الرسمية، تركز على المنهجية الدقيقة في التفسير والتحليل والاستدلال العلمي وحل وضعيات الإدماج.',
    bioFr: 'Experte en méthodologie officielle du BAC : raisonnement scientifique et schématisation génétique.',
    assignedModuleIds: ['mod-bac-sci'],
  },
  {
    id: 'tch-cherif',
    name: 'Pr. Ahmed Cherif',
    titleAr: 'مفتش تربوي ومؤلف في الأدب العربي واللغات',
    titleFr: 'Inspecteur Pédagogique en Langue & Littérature Arabes',
    specialty: 'Langue Arabe & Rhétorique',
    avatar: '📖',
    experienceYears: 22,
    institution: 'المعهد الوطني للتعليم - الجزائر',
    bioAr: 'تبسيط الإعراب، القواعد، البلاغة والنقد الأدبي بأسلوب حديث وممتع يضمن العلامة الكاملة.',
    bioFr: 'Spécialiste de la rhétorique arabe et de la dissertation littéraire au BAC.',
    assignedModuleIds: ['mod-bac-arabe'],
  },
  {
    id: 'tch-benaissa-philo',
    name: 'Pr. Fatima Zohra Benaissa',
    titleAr: 'أستاذة فلسفة ومنهجية المقالات الفكرية',
    titleFr: 'Professeure de Philosophie & Méthodologie',
    specialty: 'Philosophie & Épistémologie',
    avatar: '🧠',
    experienceYears: 15,
    institution: 'ثانوية الشهداء - وهران',
    bioAr: 'طرق مبتكرة في كتابة المقالة الفلسفية (جدلية، استقصاء بالوضع، مقارنة) مع أقوال الفلاسفة المصنفة.',
    bioFr: 'Méthodologie structurée de la dissertation philosophique et étude comparative des courants.',
    assignedModuleIds: ['mod-bac-philo'],
  },
  {
    id: 'tch-dahmani',
    name: 'Mme. Yasmine Dahmani',
    titleAr: 'أستاذة معتمدة في اللغتين الفرنسية والإنجليزية',
    titleFr: 'Enseignante Certifiée en Langues Étrangères (Français & Anglais)',
    specialty: 'Langues Étrangères & Synthèse de Texte',
    avatar: '🌍',
    experienceYears: 12,
    institution: 'جامعة الجزائر 2 - بوزريعة',
    bioAr: 'تقنيات الـ Compte-rendu objectif et critique وفنيات الـ Written Expression لنيل أعلى الدرجات.',
    bioFr: 'Techniques avancées de synthèse de documents et de rédaction pour le BAC.',
    assignedModuleIds: ['mod-bac-langues'],
  },
  {
    id: 'tch-larbi-med',
    name: 'Dr. Amina Larbi',
    titleAr: 'طبيبة وأستاذة مساعدة في علم التشريح البشري',
    titleFr: 'Médecin & Maître-Assistante en Anatomie Humaine',
    specialty: 'Anatomie & Embryologie Médicale',
    avatar: '🩺',
    experienceYears: 11,
    institution: 'كلية الطب - جامعة الجزائر 1 (زيانية)',
    bioAr: 'شرح مجسمات الأجهزة العصبية، الهيكلية والوعائية بأسلوب تفاعلي 3D لطلبة السنوات الأولى طب.',
    bioFr: 'Enseignement immersif 3D de l\'anatomie descriptive et topographique pour étudiants en médecine.',
    assignedModuleIds: ['mod-med-anat'],
  },
  {
    id: 'tch-ziani-info',
    name: 'Pr. Othman Ziani',
    titleAr: 'أستاذ باحث في هندسة البرمجيات والخوارزميات',
    titleFr: 'Enseignant-Chercheur en Génie Logiciel & Algorithmique',
    specialty: 'Algorithmes, Structures de Données & C/C++',
    avatar: '💻',
    experienceYears: 13,
    institution: 'جامعة العلوم والتكنولوجيا وهران (USTO-MB)',
    bioAr: 'حل كل مسائل امتحانات الخوارزميات، القوائم المترابطة، الأشجار الثنائية والتعقيد الحسابي.',
    bioFr: 'Maîtrise complète de la programmation modulaire, pointeurs, récursivité et complexité.',
    assignedModuleIds: ['mod-lmd-algo'],
  },
];

export const DAWARAT_PACKS: DawaaraPack[] = [
  // 1. BAC SCIENCE & MATH PACK
  {
    id: 'pack-bac-science-2026',
    slug: 'pack-bac-science-2026',
    titleAr: 'حزمة الامتياز في العلوم الدقيقة (BAC 2026)',
    titleFr: 'Pack Excellence Sciences & Mathématiques (BAC 2026)',
    titleEn: 'BAC 2026 Science & Mathematics Excellence Pack',
    category: 'BAC_SCIENCE',
    track: 'BAC',
    targetAudienceAr: 'شعبة علوم تجريبية، رياضيات وتقني رياضي (بكالوريا 2026)',
    targetAudienceFr: 'Filières Sciences Expérimentales, Mathématiques & Maths-Technique',
    badgeAr: '🔥 الحزمة الأكثر طلباً - وفر 45%',
    badgeFr: 'Top Vente - Économisez 45%',
    descriptionAr: 'برنامج تدريبي مباشر ومكثف يشمل مراجعة شاملة وحل أكثر من 30 موضوعاً نموذجياً في الرياضيات، الفيزياء، والعلوم الطبيعية مع نخبة من أفضل أساتذة الجزائر.',
    descriptionFr: 'Programme intensif en direct avec résolution de 30+ sujets types en Mathématiques, Physique-Chimie et SVT.',
    descriptionEn: 'Comprehensive live masterclass pack covering Math, Physics, and Natural Sciences with 30+ exam papers solved live.',
    originalTotalPrice: 10500,
    packPrice: 5900,
    vipDiscountPrice: 4500,
    totalHours: 54,
    totalSessions: 24,
    startDate: '2026-09-05',
    endDate: '2026-11-30',
    isLiveNow: true,
    isPopular: true,
    ambassadorId: 'amb-1',
    ambassadorName: 'Alaa Eddine (سفير العاصمة)',
    ambassadorWilayaCode: 16,
    ambassadorWilayaName: 'الجزائر العاصمة',
    referralCode: 'USTHB16',
    createdAt: '2026-08-01',
    modules: [
      {
        id: 'mod-bac-math',
        packId: 'pack-bac-science-2026',
        nameAr: 'الرياضيات - الدوال، المتتاليات والاحتمالات',
        nameFr: 'Mathématiques - Fonctions, Suites & Probabilités',
        nameEn: 'Mathematics - Functions, Sequences & Probability',
        code: 'MATH-BAC-SCI',
        coefficient: 7,
        shortDescriptionAr: 'حل مسائل الدوال الأسية واللوغارتمية، حساب النهايات، الاشتقاقية، المتتاليات التراجعية والاحتمالات المركبة.',
        shortDescriptionFr: 'Étude complète des fonctions exponentielles & logarithmiques, suites et dénombrement.',
        shortDescriptionEn: 'Full study of calculus, exponential functions, sequences, and probability.',
        syllabusAr: [
          'الدوال العددية، الأسية واللوغارتمية ورسم المنحنيات البيانية بدقة',
          'المتتاليات العددية والبرهان بالتراجع ودراسة التقارب',
          'الاحتمالات الشرطية، شجرة الإمكانيات والمتغيرات العشوائية',
          'الأعداد المركبة والتحويلات النقطية (لشعبة الرياضيات)',
        ],
        syllabusFr: [
          'Fonctions exponentielles et logarithmes népériens',
          'Suites numériques et récurrence',
          'Probabilités conditionnelles et variables aléatoires',
          'Nombres complexes et géométrie plane',
        ],
        individualPrice: 3500,
        packDiscountPrice: 2000,
        hoursCount: 18,
        sessionsCount: 8,
        scheduleDaysAr: 'الجمعة من 17:00 إلى 19:30',
        scheduleDaysFr: 'Vendredi 17h00 - 19h30',
        teacherId: 'tch-kadri',
        teacherName: 'Pr. Abdelrahim Kadri',
        teacherTitle: 'أستاذ مبرز في الرياضيات',
        teacherAvatar: '👨‍🏫',
        meetUrl: 'https://meet.dzprime.academy/live-bac-math',
        enrolledCount: 384,
      },
      {
        id: 'mod-bac-phys',
        packId: 'pack-bac-science-2026',
        nameAr: 'العلوم الفيزيائية والكيمياء الحركية',
        nameFr: 'Sciences Physiques & Chimie Cinétique',
        nameEn: 'Physics & Chemistry Masterclass',
        code: 'PHYS-BAC-SCI',
        coefficient: 6,
        shortDescriptionAr: 'المتابعة الزمنية لتحول كيميائي، التحولات النووية، الظواهر الكهربائية (RC/RL)، وميكانيك نيوتن.',
        shortDescriptionFr: 'Suivi cinétique, réactions nucléaires, circuits RC/RL et mécanique newtonienne.',
        shortDescriptionEn: 'Reaction kinetics, nuclear physics, RC/RL circuits, and Newtonian mechanics.',
        syllabusAr: [
          'المتابعة الزمنية بالناقلية والمعايرة اللونية وجدول التقدم',
          'التحولات النووية: طاقة الربط، النشاط الإشعاعي والانشطار والاندماج',
          'الدارات الكهربائية: شحن وتفريغ المكثفة والوشيعة والمعادلات التفاضلية',
          'ميكانيك نيوتن: حركة الأقمار والكواكب، السقوط الشاقولي وحركة القذائف',
        ],
        syllabusFr: [
          'Cinétique chimique et titrage conductimétrique',
          'Physique nucléaire et énergie de liaison',
          'Circuits électriques RC et RL',
          'Mécanique de Newton et trajectoires orbitales',
        ],
        individualPrice: 3500,
        packDiscountPrice: 2000,
        hoursCount: 18,
        sessionsCount: 8,
        scheduleDaysAr: 'السبت من 14:00 إلى 16:30',
        scheduleDaysFr: 'Samedi 14h00 - 16h30',
        teacherId: 'tch-mansouri',
        teacherName: 'Dr. Salim Mansouri',
        teacherTitle: 'دكتور في الفيزياء التطبيقية',
        teacherAvatar: '🔬',
        meetUrl: 'https://meet.dzprime.academy/live-bac-phys',
        enrolledCount: 342,
      },
      {
        id: 'mod-bac-sci',
        packId: 'pack-bac-science-2026',
        nameAr: 'علوم الطبيعة والحياة - المنهجية والاستدلال العلمي',
        nameFr: 'Sciences Naturelles - Raisonnement & Synthèse',
        nameEn: 'Natural Sciences & Scientific Reasoning',
        code: 'SVT-BAC-SCI',
        coefficient: 6,
        shortDescriptionAr: 'تركيب البروتين، النشاط الإنزيمي، المناعة والاتصال العصبي وفق المنهجية الرسمية لتصحيح البكالوريا.',
        shortDescriptionFr: 'Synthèse protéique, enzymologie, immunologie et transmission synaptique.',
        shortDescriptionEn: 'Protein synthesis, enzyme kinetics, immunology, and neurobiology.',
        syllabusAr: [
          'آليات التعبير المورثي وتركيب البروتين والبنية الفراغية',
          'النشاط الإنزيمي والعوامل المؤثرة عليه والتثبيط التنافسي',
          'المناعة: الذات واللاذات، الاستجابة الخلطية والخلوية وفيروس السيدا',
          'الاتصال العصبي: كمون الراحة، كمون العمل، والنقل المشبكي',
        ],
        syllabusFr: [
          'Expression génétique et conformation spatiale des protéines',
          'Cinétique enzymatique et régulation',
          'Système immunitaire et défense de l\'organisme',
          'Communication nerveuse et transmission synaptique',
        ],
        individualPrice: 3500,
        packDiscountPrice: 1900,
        hoursCount: 18,
        sessionsCount: 8,
        scheduleDaysAr: 'الأحد من 18:00 إلى 20:30',
        scheduleDaysFr: 'Dimanche 18h00 - 20h30',
        teacherId: 'tch-amrani',
        teacherName: 'Mme. Leila Amrani',
        teacherTitle: 'أستاذة رئيسية في علوم الطبيعة والحياة',
        teacherAvatar: '👩‍🔬',
        meetUrl: 'https://meet.dzprime.academy/live-bac-svt',
        enrolledCount: 310,
      },
    ],
  },

  // 2. BAC LANGUAGES & PHILOSOPHY PACK
  {
    id: 'pack-bac-languages-2026',
    slug: 'pack-bac-languages-2026',
    titleAr: 'حزمة اللغات والفلسفة المتكاملة (BAC 2026)',
    titleFr: 'Pack Langues Étrangères, Arabe & Philosophie (BAC 2026)',
    titleEn: 'BAC 2026 Languages & Philosophy Master Pack',
    category: 'BAC_LANGUAGES',
    track: 'BAC',
    targetAudienceAr: 'جميع الشعب - لغات أجنبية، آداب وفلسفة، وشعب علمية لرفع المعدل العام',
    targetAudienceFr: 'Toutes séries - Langues, Lettres & Séries Scientifiques',
    badgeAr: '⭐ حزمة رفع المعدل العام - وفر 44%',
    badgeFr: 'Boost Moyenne - Économisez 44%',
    descriptionAr: 'احصل على أعلى النقاط في المواد المرافقة: أدب عربي، فلسفة منهجية، فرنسية وإنجليزية مع تطبيقات مباشرة على نصوص البكالوريا السابقة.',
    descriptionFr: 'Maximisez votre moyenne générale avec un coaching intensif en Arabe, Philosophie, Français et Anglais.',
    descriptionEn: 'Boost your overall BAC grade with live mastery in Arabic, Philosophy, French, and English text syntheses.',
    originalTotalPrice: 8000,
    packPrice: 4500,
    vipDiscountPrice: 3500,
    totalHours: 42,
    totalSessions: 18,
    startDate: '2026-09-10',
    endDate: '2026-11-25',
    isLiveNow: true,
    ambassadorId: 'amb-2',
    ambassadorName: 'Mohamed Boualem (سفير الغرب - وهران)',
    ambassadorWilayaCode: 31,
    ambassadorWilayaName: 'وهران',
    referralCode: 'ORAN31',
    createdAt: '2026-08-05',
    modules: [
      {
        id: 'mod-bac-arabe',
        packId: 'pack-bac-languages-2026',
        nameAr: 'اللغة العربية وآدابها - البلاغة، القواعد والنقد الأدبي',
        nameFr: 'Langue Arabe - Rhétorique, Grammaire & Analyse Littéraire',
        nameEn: 'Arabic Language & Literature',
        code: 'ARB-BAC-ALL',
        coefficient: 3,
        shortDescriptionAr: 'منهجية معالجة النص الشعري والنثري، الصور البيانية، المحسنات البديعية، والإعراب التفصيلي.',
        shortDescriptionFr: 'Analyse poétique et en prose, figures de style et syntaxe avancée.',
        shortDescriptionEn: 'Poetry and prose analysis, rhetorical devices, and syntax.',
        syllabusAr: [
          'عصر الضعف والانحطاط والمدائح النبوية ومدرسة الإحياء',
          'الشعر الحر وشعر الالتزام والقضية الفلسطينية والجزائرية',
          'المقال الصحفي والنقدي وأهم رواده في الجزائر والعالم العربي',
          'الإعراب التقديري، إعراب الجمل، معاني الحروف وأدوات الاتساق والانسجام',
        ],
        syllabusFr: [
          'Courants littéraires arabes classiques et contemporains',
          'Poésie engagée et cause nationale',
          'Essai critique et articles de presse littéraires',
          'Grammaire avancée et syntaxe',
        ],
        individualPrice: 2500,
        packDiscountPrice: 1500,
        hoursCount: 14,
        sessionsCount: 6,
        scheduleDaysAr: 'الإثنين من 18:00 إلى 20:00',
        scheduleDaysFr: 'Lundi 18h00 - 20h00',
        teacherId: 'tch-cherif',
        teacherName: 'Pr. Ahmed Cherif',
        teacherTitle: 'مفتش تربوي في الأدب العربي',
        teacherAvatar: '📖',
        meetUrl: 'https://meet.dzprime.academy/live-bac-arabe',
        enrolledCount: 220,
      },
      {
        id: 'mod-bac-philo',
        packId: 'pack-bac-languages-2026',
        nameAr: 'الفلسفة - منهجية المقالات وأقوال الفلاسفة المصنفة',
        nameFr: 'Philosophie - Méthodologie des Dissertations & Thèses',
        nameEn: 'Philosophy Essay Writing & Arguments',
        code: 'PHIL-BAC-ALL',
        coefficient: 4,
        shortDescriptionAr: 'التحكم التام في الطريقة الجدلية، الاستقصاء بالوضع، تحليل النص، وفهم إشكاليات المعرفة والعلوم الإنسانية.',
        shortDescriptionFr: 'Dissertation philosophique : méthode dialectique, réquisitoire et analyse de textes.',
        shortDescriptionEn: 'Mastery of dialectical essays, defense methods, and philosophical debates.',
        syllabusAr: [
          'المنهجية الجدلية: صياغة المشكلة، الأطروحة، نقيضها، التركيب وحل المشكلة',
          'طريقة الاستقصاء بالوضع: الدفاع عن الأطروحة ومقارعة الخصوم بالأدلة',
          'إشكالية فلسفة الرياضيات، العلوم التجريبية والعلوم البيولوجية',
          'إشكالية الشعور واللاشعور، الذاكرة والخيال، والأخلاق والعدالة',
        ],
        syllabusFr: [
          'Méthodologie de la dissertation dialectique et de l\'investigation',
          'Épistémologie des mathématiques et des sciences de la nature',
          'Conscience, inconscient et mémoire',
          'Justice, droit et morale',
        ],
        individualPrice: 3000,
        packDiscountPrice: 1700,
        hoursCount: 14,
        sessionsCount: 6,
        scheduleDaysAr: 'الثلاثاء من 18:00 إلى 20:00',
        scheduleDaysFr: 'Mardi 18h00 - 20h00',
        teacherId: 'tch-benaissa-philo',
        teacherName: 'Pr. Fatima Zohra Benaissa',
        teacherTitle: 'أستاذة فلسفة وباحثة في الإبستمولوجيا',
        teacherAvatar: '🧠',
        meetUrl: 'https://meet.dzprime.academy/live-bac-philo',
        enrolledCount: 195,
      },
      {
        id: 'mod-bac-langues',
        packId: 'pack-bac-languages-2026',
        nameAr: 'اللغات الأجنبية - Compte Rendu & Written Expression',
        nameFr: 'Français & Anglais - Synthèse de Textes & Expression Écrite',
        nameEn: 'Foreign Languages - Text Synthesis & Essay Writing',
        code: 'LANG-BAC-ALL',
        coefficient: 3,
        shortDescriptionAr: 'إتقان كتابة الـ Compte-rendu critique في الفرنسية والـ Guided Essay في الإنجليزية لضمان علامة 17+.',
        shortDescriptionFr: 'Techniques infaillibles de compte-rendu objectif/critique et rédaction guidée en anglais.',
        shortDescriptionEn: 'High-scoring strategies for French text synthesis and English essays.',
        syllabusAr: [
          'Le texte d\'histoire : visée communicative et compte-rendu objectif',
          'Le texte argumentatif : argumentation et compte-rendu critique',
          'English BAC Exam Structure: Reading comprehension and vocab mastery',
          'Topic 1 & Topic 2: Argumentative and expository essay models',
        ],
        syllabusFr: [
          'Le texte d\'histoire et le texte argumentatif',
          'Rédaction du compte-rendu objectif et critique',
          'Compréhension de l\'écrit et lexique thématique en anglais',
          'Techniques de rédaction d\'essais argumentatifs',
        ],
        individualPrice: 2500,
        packDiscountPrice: 1300,
        hoursCount: 14,
        sessionsCount: 6,
        scheduleDaysAr: 'الأربعاء من 18:00 إلى 20:00',
        scheduleDaysFr: 'Mercredi 18h00 - 20h00',
        teacherId: 'tch-dahmani',
        teacherName: 'Mme. Yasmine Dahmani',
        teacherTitle: 'أستاذة معتمدة في اللغات الأجنبية',
        teacherAvatar: '🌍',
        meetUrl: 'https://meet.dzprime.academy/live-bac-langues',
        enrolledCount: 240,
      },
    ],
  },

  // 3. UNIVERSITY LMD INFORMATIQUE & MATH PACK
  {
    id: 'pack-usthb-lmd-info',
    slug: 'pack-usthb-lmd-info',
    titleAr: 'حزمة الامتياز في الإعلام الآلي والرياضيات الجامعية (LMD MI / ST)',
    titleFr: 'Pack Réussite Informatique & Mathématiques LMD (MI / ST / Ingénierie)',
    titleEn: 'University LMD Computer Science & Calculus Pack',
    category: 'UNIVERSITY_LMD',
    track: 'UNIVERSITY_LMD',
    targetAudienceAr: 'طلبة السنة الأولى والثانية جذع مشترك إعلام آلي ورياضيات وعلوم وتقنيات (L1/L2 MI & ST)',
    targetAudienceFr: 'Étudiants L1 & L2 Tronc Commun Informatique & Mathématiques',
    badgeAr: '💻 لطلبة الجامعات LMD - وفر 48%',
    badgeFr: 'Spécial Université - Économisez 48%',
    descriptionAr: 'لا خوف بعد اليوم من امتحانات EMD السداسي الأول: خوارزميات C، تحليل رياضي 1، وهندسة الحواسيب مع حل امتحانات USTHB و USTO لآخر 5 سنوات.',
    descriptionFr: 'Préparez vos EMD avec brio : Algorithmique C, Analyse 1 et Structure Machine avec annales corrigées.',
    descriptionEn: 'Master university first year algorithms in C, Calculus 1, and Computer Architecture.',
    originalTotalPrice: 10500,
    packPrice: 5500,
    vipDiscountPrice: 4200,
    totalHours: 48,
    totalSessions: 20,
    startDate: '2026-09-15',
    endDate: '2026-12-10',
    isLiveNow: true,
    ambassadorId: 'amb-1',
    ambassadorName: 'Alaa Eddine (USTHB Bab Ezzouar)',
    ambassadorWilayaCode: 16,
    ambassadorWilayaName: 'الجزائر العاصمة',
    referralCode: 'USTHB16',
    createdAt: '2026-08-08',
    modules: [
      {
        id: 'mod-lmd-algo',
        packId: 'pack-usthb-lmd-info',
        nameAr: 'الخوارزميات وهياكل البيانات بلغة C (Algo 1 & 2)',
        nameFr: 'Algorithmique & Structures de Données en Langage C',
        nameEn: 'Algorithms & Data Structures in C',
        code: 'ALGO-LMD-MI',
        coefficient: 6,
        shortDescriptionAr: 'المؤشرات (Pointers)، المصفوفات ثنائية الأبعاد، السلاسل الحرفية، السجلات والقوائم المترابطة مع التمارين التطبيقية.',
        shortDescriptionFr: 'Pointeurs, allocations dynamiques, structures, listes chaînées et complexité.',
        shortDescriptionEn: 'Pointers, dynamic allocation, structs, linked lists, and sorting algorithms.',
        syllabusAr: [
          'المفاهيم الأساسية: المتغيرات، الشروط والتكرارات (Boucles While/For)',
          'المصفوفات الأحادية والثنائية (Matrices) وعمليات البحث والترتيب',
          'المؤشرات (Pointers) وتمرير المعاملات بالعنوان وبالقيمة',
          'السجلات (Structures) والمخصصات الديناميكية (malloc / free) والقوائم',
        ],
        syllabusFr: [
          'Structures conditionnelles et itératives en C',
          'Tableaux multidimensionnels et algorithmes de tri',
          'Pointeurs et passage de paramètres par adresse',
          'Structures personnalisées et allocation dynamique de mémoire',
        ],
        individualPrice: 3800,
        packDiscountPrice: 2000,
        hoursCount: 18,
        sessionsCount: 8,
        scheduleDaysAr: 'الخميس من 18:00 إلى 20:30',
        scheduleDaysFr: 'Jeudi 18h00 - 20h30',
        teacherId: 'tch-ziani-info',
        teacherName: 'Pr. Othman Ziani',
        teacherTitle: 'أستاذ باحث في هندسة البرمجيات',
        teacherAvatar: '💻',
        meetUrl: 'https://meet.dzprime.academy/live-lmd-algo',
        enrolledCount: 290,
      },
      {
        id: 'mod-lmd-analyse',
        packId: 'pack-usthb-lmd-info',
        nameAr: 'التحليل الرياضي 1 (Analyse 1 - USTHB & USTO)',
        nameFr: 'Analyse 1 - Fonctions Réelles & Développements Limités',
        nameEn: 'Calculus 1 - Real Analysis & Taylor Expansions',
        code: 'ANAL-LMD-MI',
        coefficient: 5,
        shortDescriptionAr: 'مبرهنات القيمة المتوسطة (Rolle & TAF)، النشر المحدود (DL) بحساب النهايات وتكاملات ريمان.',
        shortDescriptionFr: 'Théorème de Rolle, TAF, formule de Taylor-Young et calcul intégral.',
        shortDescriptionEn: 'Mean value theorems, Taylor series, limits, and Riemann integration.',
        syllabusAr: [
          'المجموعات العددية وبديهية العلو (Borne Sup / Borne Inf)',
          'المتتاليات العددية والمتتاليات المتجاورة ونظرية بولزانو فايرشتراس',
          'الاشتقاقية ومبرهنة رول (Rolle) ونظرية التزايدات المنتهية (TAF)',
          'النشر المحدود (Développements Limités) وحساب أصعب النهايات',
        ],
        syllabusFr: [
          'Corps des réels, bornes supérieures et inférieures',
          'Suites numériques et théorème de Bolzano-Weierstrass',
          'Dérivabilité, théorèmes de Rolle et des accroissements finis',
          'Développements limités et calcul de limites indéterminées',
        ],
        individualPrice: 3500,
        packDiscountPrice: 1800,
        hoursCount: 16,
        sessionsCount: 6,
        scheduleDaysAr: 'الجمعة من 14:00 إلى 16:30',
        scheduleDaysFr: 'Vendredi 14h00 - 16h30',
        teacherId: 'tch-kadri',
        teacherName: 'Pr. Abdelrahim Kadri',
        teacherTitle: 'أستاذ مبرز في الرياضيات',
        teacherAvatar: '👨‍🏫',
        meetUrl: 'https://meet.dzprime.academy/live-lmd-analyse',
        enrolledCount: 260,
      },
      {
        id: 'mod-lmd-archi',
        packId: 'pack-usthb-lmd-info',
        nameAr: 'بنية الآلة والمنطق التوافقي (Structure Machine & Logique)',
        nameFr: 'Structure Machine & Logique Combinatoire',
        nameEn: 'Computer Architecture & Digital Logic',
        code: 'SM-LMD-MI',
        coefficient: 4,
        shortDescriptionAr: 'أنظمة التعداد (Binaire, Hexa)، جبر بول، جداول كارنوف، وتصميم الدارات التوافقية والتعاقبية.',
        shortDescriptionFr: 'Systèmes de numération, algèbre de Boole, tables de Karnaugh et circuits séquentiels.',
        shortDescriptionEn: 'Binary systems, Boolean algebra, Karnaugh maps, and digital circuits.',
        syllabusAr: [
          'أنظمة التعداد والتحويلات والتمثيل المتمم لـ 2 والفاصلة العائمة (IEEE 754)',
          'جبر بول وتبسيط الدوال المنطقية بواسطة جداول كارنوف (Karnaugh)',
          'الدارات التوافقية: الجامع (Additionneur)، المشفر والمفكك والموزع',
          'مقدمة في المسجلات والقلابات (Bascules RS, D, JK)',
        ],
        syllabusFr: [
          'Systèmes de numération et représentation en virgule flottante',
          'Algèbre de Boole et simplification par tables de Karnaugh',
          'Circuits combinatoires : additionneurs, multiplexeurs, décodeurs',
          'Circuits séquentiels élémentaires : bascules et registres',
        ],
        individualPrice: 3200,
        packDiscountPrice: 1700,
        hoursCount: 14,
        sessionsCount: 6,
        scheduleDaysAr: 'السبت من 18:00 إلى 20:00',
        scheduleDaysFr: 'Samedi 18h00 - 20h00',
        teacherId: 'tch-mansouri',
        teacherName: 'Dr. Salim Mansouri',
        teacherTitle: 'دكتور في الفيزياء والإلكترونيات',
        teacherAvatar: '🔬',
        meetUrl: 'https://meet.dzprime.academy/live-lmd-archi',
        enrolledCount: 215,
      },
    ],
  },

  // 4. MEDICAL SCIENCES PRE-CLINIQUE PACK
  {
    id: 'pack-med-preclinique-2026',
    slug: 'pack-med-preclinique-2026',
    titleAr: 'حزمة مراجعة العلوم الطبية (Pre-Clinique Masterclass)',
    titleFr: 'Pack Révision Sciences Médicales (Médecine 1ère & 2ème Année)',
    titleEn: 'Medical Sciences Pre-Clinical Masterclass Pack',
    category: 'MEDICAL',
    track: 'MEDICAL',
    targetAudienceAr: 'طلبة كليات الطب، الصيدلة وطب الأسنان (السنة الأولى والثانية)',
    targetAudienceFr: 'Étudiants en Médecine, Pharmacie et Médecine Dentaire',
    badgeAr: '🩺 مراجعة QCM الشاملة لكليات الطب',
    badgeFr: 'Spécial Médecine - Annales QCM',
    descriptionAr: 'مراجعة تشريحية وفيزيولوجية مركزة تشمل حل مئات أسئلة الـ QCM لامتحانات كليات الطب في الجزائر العاصمة، وهران وقسنطينة.',
    descriptionFr: 'Masterclass médicale avec résolution de centaines de QCMs d\'anatomie, physiologie et histologie.',
    descriptionEn: 'Intensive medical review covering Anatomy, Physiology, and MCQ mastery for Algerian medical faculties.',
    originalTotalPrice: 13000,
    packPrice: 7500,
    vipDiscountPrice: 6000,
    totalHours: 50,
    totalSessions: 22,
    startDate: '2026-09-20',
    endDate: '2026-12-15',
    isLiveNow: true,
    ambassadorId: 'amb-3',
    ambassadorName: 'Sara Cherif (سفيرة الشرق - قسنطينة)',
    ambassadorWilayaCode: 25,
    ambassadorWilayaName: 'قسنطينة',
    referralCode: 'MED25',
    createdAt: '2026-08-10',
    modules: [
      {
        id: 'mod-med-anat',
        packId: 'pack-med-preclinique-2026',
        nameAr: 'التشريح البشري العام وعلم العظام والمفاصل (Anatomie Générale)',
        nameFr: 'Anatomie Humaine & Ostéo-Arthrologie Descriptive',
        nameEn: 'Human Anatomy & Osteology',
        code: 'ANAT-MED-1',
        coefficient: 6,
        shortDescriptionAr: 'التشريح الوصفي للطرف العلوي والسفلي، القفص الصدري، العمود الفقري وعضلات الجدار البطني.',
        shortDescriptionFr: 'Anatomie du membre supérieur, membre inférieur, thorax et rachis.',
        shortDescriptionEn: 'Descriptive anatomy of limbs, thorax, and vertebral column.',
        syllabusAr: [
          'عظام ومفاصل الطرف العلوي: عظم العضد، الترقوة، لوح الكتف والمفصل الكتفي',
          'عظام الطرف السفلي: عظم الفخذ، الرضفة، الظنبوب، الشظية وقوس القدم',
          'تشريح القفص الصدري وعضلات التنفس والقلب والأوعية الكبرى',
          'حل بنك أسئلة الـ QCM لامتحانات الجزائر 1، قسنطينة 3 ووهران 1',
        ],
        syllabusFr: [
          'Ostéologie et arthrologie du membre supérieur et inférieur',
          'Anatomie du thorax, médiastin et vascularisation',
          'Rachis vertébral et biomécanique',
          'Entraînement intensif sur les banques de QCM médicales',
        ],
        individualPrice: 4500,
        packDiscountPrice: 2800,
        hoursCount: 20,
        sessionsCount: 8,
        scheduleDaysAr: 'الأحد من 18:00 إلى 20:30',
        scheduleDaysFr: 'Dimanche 18h00 - 20h30',
        teacherId: 'tch-larbi-med',
        teacherName: 'Dr. Amina Larbi',
        teacherTitle: 'طبيبة وأستاذة مساعدة في علم التشريح',
        teacherAvatar: '🩺',
        meetUrl: 'https://meet.dzprime.academy/live-med-anat',
        enrolledCount: 210,
      },
    ],
  },
];


export const AMBASSADORS: AmbassadorProfile[] = [
  {
    id: 'amb-1',
    userId: 'user-ambassador',
    user: DEMO_USERS[1],
    wilayaCode: 16,
    wilayaNameAr: 'الجزائر العاصمة',
    institutionId: 'inst-usthb',
    institutionNameAr: 'جامعة العلوم والتكنولوجيا USTHB',
    bioAr: 'سفير منصة DZ Prime Academy بجامعة باب الزوار. مسؤول عن تنظيم الفعاليات، حصص المراجعة ونشر مواضيع الامتحانات وحلولها لطلبة الإعلام الآلي والرياضيات.',
    bioFr: "Ambassadeur officiel DZ Prime à l'USTHB Bab Ezzouar. Coordination des sessions de révision et partage des annales corrigées en Math & Informatique.",
    ratingAverage: 4.95,
    ratingsCount: 148,
    isVerified: true,
    upcomingSessionsCount: 3,
    totalTipsShared: 42,
  },
  {
    id: 'amb-2',
    userId: 'user-amb-oran',
    user: {
      id: 'user-amb-oran',
      email: 'ambassador.oran@dzprime.academy',
      name: 'Mohamed Boualem',
      role: 'AMBASSADOR',
      wilayaCode: 31,
      wilayaName: 'Oran',
      institutionId: 'inst-usto',
      institutionName: 'Université USTO-MB',
      studentCardId: 'DZ-AMB-31-0321',
      isVerified: true,
      createdAt: '2023-10-01',
    },
    wilayaCode: 31,
    wilayaNameAr: 'وهران',
    institutionId: 'inst-usto',
    institutionNameAr: 'جامعة العلوم والتكنولوجيا وهران (USTO)',
    bioAr: 'سفير المنصة لولاية وهران وجامعة إيسطو. دعم مستمر لطلبة الهندسة والعلوم الدقيقة.',
    bioFr: "Ambassadeur DZ Prime pour la wilaya d'Oran et l'université USTO. Soutien académique continu en Sciences et Ingénierie.",
    ratingAverage: 4.88,
    ratingsCount: 94,
    isVerified: true,
    upcomingSessionsCount: 2,
    totalTipsShared: 29,
  },
  {
    id: 'amb-3',
    userId: 'user-amb-constantine',
    user: {
      id: 'user-amb-constantine',
      email: 'ambassador.constantine@dzprime.academy',
      name: 'Sara Cherif',
      role: 'AMBASSADOR',
      wilayaCode: 25,
      wilayaName: 'Constantine',
      institutionId: 'inst-mentouri',
      institutionName: 'Université Frères Mentouri',
      studentCardId: 'DZ-AMB-25-0552',
      isVerified: true,
      createdAt: '2023-10-15',
    },
    wilayaCode: 25,
    wilayaNameAr: 'قسنطينة',
    institutionId: 'inst-mentouri',
    institutionNameAr: 'جامعة الإخوة منتوري قسنطينة 1',
    bioAr: 'سفيرة الشرق الجزائري - قسنطينة. توجيه الطلبة الجدد، تنظيم نوادي علمية وحلقات دراسية.',
    bioFr: "Ambassadrice de l'Est Algérien à Constantine 1. Orientation des nouveaux étudiants et organisation de groupes d'étude.",
    ratingAverage: 4.92,
    ratingsCount: 112,
    isVerified: true,
    upcomingSessionsCount: 4,
    totalTipsShared: 37,
  }
];

export const RECENT_POSTS: Post[] = [
  {
    id: 'post-1',
    title: 'حصة مراجعة شاملة وحضورية في مادة التحليل 1 (Analyse 1) قبل امتحانات السداسي الأول',
    content: 'يسر سفارة منصة DZ Prime بجامعة USTHB الإعلان عن تنظيم ورشة مراجعة حضورية مكثفة تشمل حل 4 مواضيع امتحانات سابقة مع شرح أفكار الدوال، المتتاليات والاستمرار. المكان: قاعة المحاضرات C - باب الزوار.',
    type: 'SESSION_SCHEDULE',
    wilayaCode: 16,
    wilayaName: 'الجزائر العاصمة',
    institutionId: 'inst-usthb',
    institutionName: 'جامعة USTHB',
    eventDate: '2026-08-25T10:00:00Z',
    isOnline: false,
    location: 'قاعة المحاضرات C - كلية الرياضيات (USTHB)',
    isApproved: true,
    authorId: 'user-ambassador',
    authorName: 'Alaa Eddine (Ambassadeur USTHB)',
    authorRole: 'AMBASSADOR',
    createdAt: '2026-08-14',
  },
  {
    id: 'post-2',
    title: 'نصائح ذهبية لطلبة البكالوريا: كيف تنظم وقتك في شهر ما قبل الدخول المدرسي؟',
    content: 'خطوات منهجية وضعها أوائل البكالوريا في الجزائر: 1. تثبيت الأساسيات في الرياضيات والمكتسبات القبلية، 2. مراجعة مصطلحات وشخصيات التاريخ والجغرافيا بذكاء، 3. عدم الضغط النفسي وتحديد هدف معدل الامتياز.',
    type: 'STUDY_TIP',
    wilayaCode: 16,
    wilayaName: 'الجزائر العاصمة',
    isOnline: true,
    isApproved: true,
    authorId: 'user-admin',
    authorName: 'Conseil National DZ Prime',
    authorRole: 'OWNER',
    createdAt: '2026-08-13',
  },
  {
    id: 'post-3',
    title: 'لايف مباشر عبر زووم: حل مسائل المصفوفات والفضاءات الشعاعية (Algèbre 1)',
    content: 'جلسة تدريبية تفاعلية ومجانية لجميع طلبة L1 MI و L1 ST مع الأستاذ قادري وسفراء المنصة. رابط الزووم متاح في قسم الأحداث بالمنصة.',
    type: 'EVENT',
    wilayaCode: 19,
    wilayaName: 'سطيف',
    eventDate: '2026-08-28T20:00:00Z',
    isOnline: true,
    meetUrl: 'https://meet.dzprime.academy/live-algebra-1',
    isApproved: true,
    authorId: 'user-teacher-1',
    authorName: 'Pr. Karim Kadri (Algèbre)',
    authorRole: 'TEACHER',
    createdAt: '2026-08-12',
  },
];

export const MODULE_RESOURCES: ModuleResource[] = [
  {
    id: 'res-1',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل (BAC)',
    title: 'سلسلة الامتياز 01: مسائل الدوال الأسية واللوغاريتمية الشاملة مع الحل المفصل',
    fileType: 'PDF_SERIES',
    fileUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    fileSize: '4.8 MB',
    uploadedBy: 'Pr. Abdelrahim Kadri',
    uploadedAt: '2026-08-15',
    downloadCount: 342,
  },
  {
    id: 'res-2',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل (BAC)',
    title: 'بنك مواضيع المتتاليات العددية (2015-2025) مع سلم التنقيط الوزاري',
    fileType: 'SOLUTION_KEY',
    fileUrl: '/exams/samples/bac_suites_corriges.pdf',
    fileSize: '6.2 MB',
    uploadedBy: 'Pr. Abdelrahim Kadri',
    uploadedAt: '2026-08-18',
    downloadCount: 512,
  },
  {
    id: 'res-3',
    moduleId: 'mod-bac-phys',
    moduleName: 'الفيزياء والكيمياء الحركية (BAC)',
    title: 'خريطة ذهنية لجميع قوانين الميكانيك وحركة الكواكب والأقمار الاصطناعية',
    fileType: 'MINDMAP',
    fileUrl: '/exams/samples/physique_mecanique_mindmap.pdf',
    fileSize: '2.1 MB',
    uploadedBy: 'Dr. Salim Mansouri',
    uploadedAt: '2026-08-19',
    downloadCount: 420,
  },
  {
    id: 'res-4',
    moduleId: 'mod-lmd-analyse',
    moduleName: 'Analyse 1 & 2 (MI L1)',
    title: 'Série de TD 01: Suites Numériques, Bornes Sup/Inf & Développements Limités (USTHB & Mentouri)',
    fileType: 'PDF_SERIES',
    fileUrl: '/exams/samples/lmd_analyse1_td1.pdf',
    fileSize: '3.4 MB',
    uploadedBy: 'Pr. Abdelrahim Kadri',
    uploadedAt: '2026-08-14',
    downloadCount: 289,
  },
  {
    id: 'res-5',
    moduleId: 'mod-med-anat',
    moduleName: 'Anatomie Humaine & QCMs',
    title: 'Banque Officielle 200+ QCMs Corrigés d\'Ostéologie & Membre Supérieur (Alger 1 & Oran 1)',
    fileType: 'PDF_SERIES',
    fileUrl: '/exams/samples/med_anat_qcm_pack.pdf',
    fileSize: '8.5 MB',
    uploadedBy: 'Dr. Amina Larbi',
    uploadedAt: '2026-08-16',
    downloadCount: 395,
  },
];

export const SAMPLE_ROSTER_STUDENTS: TeacherRosterStudent[] = [
  {
    id: 'stu-rost-1',
    studentName: 'Ines Haddad',
    avatar: '👩‍🎓',
    wilayaCode: 31,
    wilayaName: 'Oran',
    institution: 'Université USTO-MB',
    moduleId: 'mod-lmd-analyse',
    moduleName: 'Analyse 1 & 2 (MI L1)',
    enrolledAt: '2026-08-10',
    attendanceRate: 96,
    lastAttendedSession: 'Vendredi 22 Août - Séance 4',
    status: 'ACTIVE',
  },
  {
    id: 'stu-rost-2',
    studentName: 'Yacine Belalem',
    avatar: '👨‍🎓',
    wilayaCode: 16,
    wilayaName: 'Alger',
    institution: 'Lycée Frantz Fanon (Bab El Oued)',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل (BAC)',
    enrolledAt: '2026-08-12',
    attendanceRate: 100,
    lastAttendedSession: 'السبت 23 أوت - الحصة 3',
    status: 'ACTIVE',
  },
  {
    id: 'stu-rost-3',
    studentName: 'Amina Zerrouki',
    avatar: '🧕',
    wilayaCode: 25,
    wilayaName: 'Constantine',
    institution: 'Faculté de Médecine Constantine 3',
    moduleId: 'mod-med-anat',
    moduleName: 'Anatomie Humaine & QCMs',
    enrolledAt: '2026-08-14',
    attendanceRate: 90,
    lastAttendedSession: 'الأحد 24 أوت - الحصة 2',
    status: 'ACTIVE',
  },
  {
    id: 'stu-rost-4',
    studentName: 'Walid Mansour',
    avatar: '👨‍💻',
    wilayaCode: 19,
    wilayaName: 'Sétif',
    institution: 'Université Ferhat Abbas Sétif 1',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل (BAC)',
    enrolledAt: '2026-08-15',
    attendanceRate: 88,
    lastAttendedSession: 'الجمعة 22 أوت - الحصة 3',
    status: 'ACTIVE',
  },
  {
    id: 'stu-rost-5',
    studentName: 'Meriem Benali',
    avatar: '👩‍🔬',
    wilayaCode: 9,
    wilayaName: 'Blida',
    institution: 'Lycée Ibn Rouchd Blida',
    moduleId: 'mod-bac-phys',
    moduleName: 'الفيزياء والكيمياء الحركية (BAC)',
    enrolledAt: '2026-08-16',
    attendanceRate: 94,
    lastAttendedSession: 'الإثنين 25 أوت - الحصة 2',
    status: 'ACTIVE',
  },
];

export const AMBASSADOR_SALES: AmbassadorSaleRecord[] = [
  {
    id: 'sale-1',
    studentName: 'Yacine Belalem',
    packTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    promoCode: 'USTHB16',
    commissionAmount: 590,
    date: '2026-08-20',
    status: 'PAID',
  },
  {
    id: 'sale-2',
    studentName: 'Rayane Khelifi',
    packTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    promoCode: 'USTHB16',
    commissionAmount: 590,
    date: '2026-08-21',
    status: 'PAID',
  },
  {
    id: 'sale-3',
    studentName: 'Lina Bouzid',
    packTitle: 'حزمة مراجعة اللغات والفلسفة (BAC 2026)',
    promoCode: 'USTHB16',
    commissionAmount: 490,
    date: '2026-08-22',
    status: 'PENDING_PAYOUT',
  },
  {
    id: 'sale-4',
    studentName: 'Karim Sahli',
    packTitle: 'حزمة مراجعة السنة الأولى جامعي (LMD CS & Math)',
    promoCode: 'ORAN31',
    commissionAmount: 650,
    date: '2026-08-23',
    status: 'PAID',
  },
  {
    id: 'sale-5',
    studentName: 'Chaima Touati',
    packTitle: 'حزمة مراجعة العلوم الطبية (Pre-Clinique)',
    promoCode: 'MED25',
    commissionAmount: 750,
    date: '2026-08-24',
    status: 'PENDING_PAYOUT',
  },
];

export const INITIAL_ENROLLMENTS: PackEnrollment[] = [
  {
    id: 'enr-1',
    studentId: 'user-student-gold',
    studentName: 'Ines Haddad',
    studentEmail: 'student.gold@dzprime.academy',
    studentPhone: '+213 550 44 33 22',
    packId: 'pack-bac-science-2026',
    packTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    moduleIds: ['mod-bac-math', 'mod-bac-phys', 'mod-bac-snv'],
    totalPaid: 4500,
    paymentMethod: 'EDAHABIA',
    referralCodeUsed: 'USTHB16',
    ambassadorDiscountApplied: 500,
    status: 'CONFIRMED',
    receiptUrl: 'DZ-DAW-884102',
    createdAt: '2026-08-18',
  },
];


// Sample realistic student attendees for BAC & University live masterclasses
export const SAMPLE_BAC_ATTENDEES = [
  {
    id: 'att-1',
    studentName: 'أنيس حاج صحراوي (Anis Hadj-Sahraoui)',
    avatar: '👨‍🎓',
    wilayaCode: 16,
    wilayaName: 'الجزائر العاصمة',
    institution: 'ثانوية الرياضيات بالقبة (Lycée des Mathématiques)',
    specialty: '3AS - رياضيات (3ème Année Mathématiques)',
    joinedAt: '17:54 (قبل البث بـ 6 د)',
    status: 'PRESENT' as const,
    handRaised: true,
    audioActive: false,
    notes: 'طالب متميز، متفاعل في حل المسألة رقم 4',
  },
  {
    id: 'att-2',
    studentName: 'لينا بلقاسم (Lyna Belkacem)',
    avatar: '👩‍🎓',
    wilayaCode: 31,
    wilayaName: 'وهران',
    institution: 'ثانوية العقيد لطفي - وهران',
    specialty: '3AS - علوم تجريبية (Sciences Exp)',
    joinedAt: '17:58',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: false,
    notes: 'طرحت سؤال حول نهاية الدالة اللوغاريتمية بالتركيب',
  },
  {
    id: 'att-3',
    studentName: 'ياسين قدور (Yacine Kaddour)',
    avatar: '👨‍🎓',
    wilayaCode: 25,
    wilayaName: 'قسنطينة',
    institution: 'ثانوية الإخوة كواشي - قسنطينة',
    specialty: '3AS - تقني رياضي (Génie Civil)',
    joinedAt: '18:02',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: true,
    notes: 'شارك في الإجابة الصوتية على السؤال النظري',
  },
  {
    id: 'att-4',
    studentName: 'رانيا منصوري (Rania Mansouri)',
    avatar: '👩‍🎓',
    wilayaCode: 19,
    wilayaName: 'سطيف',
    institution: 'ثانوية مالك بن نبي - سطيف',
    specialty: '3AS - علوم تجريبية (Sciences Exp)',
    joinedAt: '18:00',
    status: 'PRESENT' as const,
    handRaised: true,
    audioActive: false,
    notes: 'سؤال حول مبرهنة رول ونقاط الانعطاف',
  },
  {
    id: 'att-5',
    studentName: 'مهدي بومدين (Mehdi Boumediene)',
    avatar: '👨‍🎓',
    wilayaCode: 9,
    wilayaName: 'البليدة',
    institution: 'ثانوية الفتح - البليدة',
    specialty: '3AS - رياضيات (Mathématiques)',
    joinedAt: '18:05',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: false,
  },
  {
    id: 'att-6',
    studentName: 'نور الهدى إيدير (Nour El Houda Idir)',
    avatar: '👩‍🎓',
    wilayaCode: 15,
    wilayaName: 'تيزي وزو',
    institution: 'ثانوية عبان رمضان - تيزي وزو',
    specialty: '3AS - علوم تجريبية (Sciences Exp)',
    joinedAt: '17:56',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: false,
  },
  {
    id: 'att-7',
    studentName: 'كريم بن عابد (Karim Benabed)',
    avatar: '👨‍🎓',
    wilayaCode: 13,
    wilayaName: 'تلمسان',
    institution: 'ثانوية بن زرجب - تلمسان',
    specialty: '3AS - تقني رياضي',
    joinedAt: '18:01',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: false,
  },
  {
    id: 'att-8',
    studentName: 'أميرة سعيدي (Amira Saidi)',
    avatar: '👩‍🎓',
    wilayaCode: 5,
    wilayaName: 'باتنة',
    institution: 'ثانوية زروقي مروان - باتنة',
    specialty: '3AS - علوم تجريبية',
    joinedAt: '18:00',
    status: 'PRESENT' as const,
    handRaised: true,
    audioActive: false,
  },
  {
    id: 'att-9',
    studentName: 'وليد جبار (Walid Djebbar)',
    avatar: '👨‍🎓',
    wilayaCode: 16,
    wilayaName: 'الجزائر العاصمة',
    institution: 'ثانوية الشيخ بوعمامة - المرادية',
    specialty: '3AS - علوم تجريبية',
    joinedAt: '—',
    status: 'EXCUSED' as const,
    notes: 'مبرر بداعي إجراء فحص طبي',
  },
  {
    id: 'att-10',
    studentName: 'سفيان براهمي (Sofiane Brahimi)',
    avatar: '👨‍🎓',
    wilayaCode: 6,
    wilayaName: 'بجاية',
    institution: 'ثانوية طاهري عبد الرحمن - بجاية',
    specialty: '3AS - رياضيات',
    joinedAt: '—',
    status: 'ABSENT' as const,
  },
];

export const SAMPLE_LMD_ATTENDEES = [
  {
    id: 'att-u1',
    studentName: 'أسامة بوشارب (Oussama Bouchareb)',
    avatar: '👨‍💻',
    wilayaCode: 16,
    wilayaName: 'الجزائر العاصمة',
    institution: 'جامعة العلوم والتكنولوجيا هواري بومدين (USTHB)',
    specialty: 'L1 Tronc Commun Informatique & Math (MI)',
    joinedAt: '19:55',
    status: 'PRESENT' as const,
    handRaised: true,
    audioActive: false,
    notes: 'سؤال حول مصفوفة التحويل والتطبيقات التراجعية',
  },
  {
    id: 'att-u2',
    studentName: 'مريم زياني (Meriem Ziani)',
    avatar: '👩‍💻',
    wilayaCode: 31,
    wilayaName: 'وهران',
    institution: 'جامعة العلوم والتكنولوجيا وهران (USTO-MB)',
    specialty: 'L1 Tronc Commun MI',
    joinedAt: '19:59',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: false,
  },
  {
    id: 'att-u3',
    studentName: 'حسام دراجي (Houssam Derradji)',
    avatar: '👨‍💻',
    wilayaCode: 25,
    wilayaName: 'قسنطينة',
    institution: 'جامعة عبد الحميد مهري قسنطينة 2 (NTIC)',
    specialty: 'L2 Informatique Système',
    joinedAt: '20:01',
    status: 'PRESENT' as const,
    handRaised: true,
    audioActive: true,
  },
  {
    id: 'att-u4',
    studentName: 'إيمان شنتوف (Imene Chentouf)',
    avatar: '👩‍💻',
    wilayaCode: 19,
    wilayaName: 'سطيف',
    institution: 'جامعة فرحات عباس سطيف 1',
    specialty: 'L1 MI',
    joinedAt: '20:00',
    status: 'PRESENT' as const,
    handRaised: false,
    audioActive: false,
  },
];

export const TEACHER_LIVE_SESSIONS: TeacherLiveSession[] = [
  {
    id: 'sess-1',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 1,
    title: '01. دراسة الدوال العددية والاشتقاقية ونقاط الانعطاف المعقدة',
    date: '2026-08-10',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-1',
    ambassadorName: 'علاء الدين (Alaa Eddine)',
    ambassadorWilayaCode: 16,
    ambassadorWilayaName: 'الجزائر العاصمة',
    ambassadorAvatar: '🌟',
    ambassadors: [
      {
        id: 'amb-1',
        name: 'علاء الدين (Alaa Eddine)',
        wilayaCode: 16,
        wilayaName: 'الجزائر العاصمة',
        institution: 'جامعة العلوم والتكنولوجيا USTHB',
        roleTitle: 'منسق عام ومشرف قاعة البث (Host Moderator)',
        avatar: '🌟',
      },
      {
        id: 'amb-2',
        name: 'سامي بوزيد (Sami Bouzid)',
        wilayaCode: 31,
        wilayaName: 'وهران',
        institution: 'ثانويات الغرب الجزائري وجامعة USTO',
        roleTitle: 'منسق طلبة الغرب ونوادي الرياضيات',
        avatar: '👨‍💼',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 168,
    replayViewsCount: 380,
    questionsCount: 42,
    meetUrl: '/room/room-math-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 01: الاشتقاقية ودراسة الدوال العددية.pdf',
    recordingUrl: 'https://replay.dzprime.academy/math-kadri-sess1',
  },
  {
    id: 'sess-2',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 2,
    title: '02. المتتاليات العددية والبرهان بالتراجع وحساب المجاميع والنهايات',
    date: '2026-08-14',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-2',
    ambassadorName: 'سامي بوزيد (Sami Bouzid)',
    ambassadorWilayaCode: 31,
    ambassadorWilayaName: 'وهران',
    ambassadorAvatar: '👨‍💼',
    ambassadors: [
      {
        id: 'amb-2',
        name: 'سامي بوزيد (Sami Bouzid)',
        wilayaCode: 31,
        wilayaName: 'وهران',
        institution: 'جامعة العلوم والتكنولوجيا وهران (USTO)',
        roleTitle: 'مشرف الجلسة والمناقشة التطبيقية',
        avatar: '👨‍💼',
      },
      {
        id: 'amb-3',
        name: 'مريم شطاح (Meriem Chettih)',
        wilayaCode: 25,
        wilayaName: 'قسنطينة',
        institution: 'جامعة الإخوة منتوري قسنطينة 1',
        roleTitle: 'مسؤولة الأسئلة والشات التفاعلي',
        avatar: '👩‍🎓',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 172,
    replayViewsCount: 410,
    questionsCount: 38,
    meetUrl: '/room/room-math-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 02: المتتاليات والمجاميع المعقدة.pdf',
    recordingUrl: 'https://replay.dzprime.academy/math-kadri-sess2',
  },
  {
    id: 'sess-3',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 3,
    title: '03. الدوال الأسية واللوغاريتمية وحل مسائل البكالوريا السابقة 2024/2025',
    date: '2026-08-18',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-3',
    ambassadorName: 'مريم شطاح (Meriem Chettih)',
    ambassadorWilayaCode: 25,
    ambassadorWilayaName: 'قسنطينة',
    ambassadorAvatar: '👩‍🎓',
    ambassadors: [
      {
        id: 'amb-3',
        name: 'مريم شطاح (Meriem Chettih)',
        wilayaCode: 25,
        wilayaName: 'قسنطينة',
        institution: 'جامعة الإخوة منتوري قسنطينة 1',
        roleTitle: 'منسقة الشرق ومراجعة نماذج البكالوريا',
        avatar: '👩‍🎓',
      },
      {
        id: 'amb-1',
        name: 'علاء الدين (Alaa Eddine)',
        wilayaCode: 16,
        wilayaName: 'الجزائر العاصمة',
        institution: 'جامعة USTHB',
        roleTitle: 'إدارة البث السحابي والتسجيل',
        avatar: '🌟',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 164,
    replayViewsCount: 350,
    questionsCount: 45,
    meetUrl: '/room/room-math-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 03: حلول مسائل البكالوريا الوزارية.pdf',
    recordingUrl: 'https://replay.dzprime.academy/math-kadri-sess3',
  },
  {
    id: 'sess-4',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 4,
    title: '04. الحساب التكاملي وحساب المساحات الهندسية وحجوم المجسمات الدورانية',
    date: '2026-08-22',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-4',
    ambassadorName: 'فريد خليفي (Farid Khelifi)',
    ambassadorWilayaCode: 19,
    ambassadorWilayaName: 'سطيف',
    ambassadorAvatar: '👨‍🎓',
    ambassadors: [
      {
        id: 'amb-4',
        name: 'فريد خليفي (Farid Khelifi)',
        wilayaCode: 19,
        wilayaName: 'سطيف',
        institution: 'جامعة فرحات عباس سطيف 1',
        roleTitle: 'منسق الهضاب العليا وورشات التكامل',
        avatar: '👨‍🎓',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 170,
    replayViewsCount: 290,
    questionsCount: 50,
    meetUrl: '/room/room-math-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 04: التكاملات وحساب المساحات.pdf',
    recordingUrl: 'https://replay.dzprime.academy/math-kadri-sess4',
  },
  {
    id: 'sess-5',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 5,
    title: '05. الهندسة الفضائية: الجداء السلمي، المستويات المتعامدة، والمسافة بين نقطة ومستوي',
    date: '2026-08-26',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-1',
    ambassadorName: 'علاء الدين (Alaa Eddine)',
    ambassadorWilayaCode: 16,
    ambassadorWilayaName: 'الجزائر العاصمة',
    ambassadorAvatar: '🌟',
    ambassadors: [
      {
        id: 'amb-1',
        name: 'علاء الدين (Alaa Eddine)',
        wilayaCode: 16,
        wilayaName: 'الجزائر العاصمة',
        institution: 'جامعة USTHB',
        roleTitle: 'مشرف القاعة الرئيسي',
        avatar: '🌟',
      },
      {
        id: 'amb-2',
        name: 'سامي بوزيد (Sami Bouzid)',
        wilayaCode: 31,
        wilayaName: 'وهران',
        institution: 'جامعة USTO',
        roleTitle: 'منسق التمارين الفضائية',
        avatar: '👨‍💼',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 175,
    replayViewsCount: 180,
    questionsCount: 33,
    meetUrl: '/room/room-math-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 05: الهندسة الفضائية التفاعلية.pdf',
    recordingUrl: 'https://replay.dzprime.academy/math-kadri-sess5',
  },
  {
    id: 'sess-6',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 6,
    title: '06. الاحتمالات الشرطية والمتغير العشوائي وشجرة الاحتمالات وقانون برنولي',
    date: '2026-08-28',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-1',
    ambassadorName: 'علاء الدين (Alaa Eddine)',
    ambassadorWilayaCode: 16,
    ambassadorWilayaName: 'الجزائر العاصمة',
    ambassadorAvatar: '🌟',
    ambassadors: [
      {
        id: 'amb-1',
        name: 'علاء الدين (Alaa Eddine)',
        wilayaCode: 16,
        wilayaName: 'الجزائر العاصمة',
        institution: 'جامعة USTHB (الجزائر)',
        roleTitle: 'المشرف التقني وإدارة البث المباشر',
        avatar: '🌟',
      },
      {
        id: 'amb-2',
        name: 'سامي بوزيد (Sami Bouzid)',
        wilayaCode: 31,
        wilayaName: 'وهران',
        institution: 'جامعة USTO (وهران)',
        roleTitle: 'منسق نوادي الرياضيات والغرب',
        avatar: '👨‍💼',
      },
      {
        id: 'amb-3',
        name: 'مريم شطاح (Meriem Chettih)',
        wilayaCode: 25,
        wilayaName: 'قسنطينة',
        institution: 'جامعة منتوري قسنطينة 1 (الشرق)',
        roleTitle: 'منسقة الشات التفاعلي والأسئلة',
        avatar: '👩‍🎓',
      },
      {
        id: 'amb-4',
        name: 'فريد خليفي (Farid Khelifi)',
        wilayaCode: 19,
        wilayaName: 'سطيف',
        institution: 'جامعة فرحات عباس سطيف 1',
        roleTitle: 'مسؤول الحضور وتقييم الطلبة',
        avatar: '👨‍🎓',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 165,
    replayViewsCount: 45,
    questionsCount: 28,
    meetUrl: '/room/room-math-kadri',
    status: 'LIVE_NOW',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 06: الاحتمالات والمتغير العشوائي 2026.pdf',
    recordingUrl: '',
  },
  {
    id: 'sess-7',
    roomId: 'room-math-kadri',
    moduleId: 'mod-bac-math',
    moduleName: 'الرياضيات والتحليل الرياضي (BAC 2026)',
    courseTitle: 'حزمة البكالوريا علوم تجريبية ورياضيات 2026',
    sessionNumber: 7,
    title: '07. ورشة حل المسائل الإدماجية المعقدة ومبرهنة القيم المتوسطة ونقاط الانعطاف',
    date: '2026-08-31',
    timeSlot: '18:00 - 19:30',
    durationMinutes: 90,
    ambassadorId: 'amb-3',
    ambassadorName: 'مريم شطاح (Meriem Chettih)',
    ambassadorWilayaCode: 25,
    ambassadorWilayaName: 'قسنطينة',
    ambassadorAvatar: '👩‍🎓',
    ambassadors: [
      {
        id: 'amb-3',
        name: 'مريم شطاح (Meriem Chettih)',
        wilayaCode: 25,
        wilayaName: 'قسنطينة',
        institution: 'جامعة منتوري قسنطينة 1',
        roleTitle: 'منسقة الجلسة المباشرة',
        avatar: '👩‍🎓',
      },
      {
        id: 'amb-1',
        name: 'علاء الدين (Alaa Eddine)',
        wilayaCode: 16,
        wilayaName: 'الجزائر العاصمة',
        institution: 'جامعة USTHB',
        roleTitle: 'إشراف تقني',
        avatar: '🌟',
      },
    ],
    attendees: SAMPLE_BAC_ATTENDEES,
    enrolledStudentsCount: 180,
    joinedStudentsCount: 0,
    replayViewsCount: 0,
    questionsCount: 0,
    meetUrl: '/room/room-math-kadri',
    status: 'SCHEDULED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'سلسلة 07: المسائل الشاملة للامتياز.pdf',
  },
  {
    id: 'sess-8',
    roomId: 'room-lmd-kadri',
    moduleId: 'mod-lmd-analyse',
    moduleName: 'التحليل الرياضي والجبر الخطي (LMD MI L1)',
    courseTitle: 'حزمة مراجعة السنة الأولى جامعي (LMD CS & Math)',
    sessionNumber: 1,
    title: '01. الفضاءات الشعاعية والتطبيقات الخطية وحساب القيم الذاتية والمصفوفات',
    date: '2026-08-12',
    timeSlot: '20:00 - 21:30',
    durationMinutes: 90,
    ambassadorId: 'amb-1',
    ambassadorName: 'علاء الدين (Alaa Eddine)',
    ambassadorWilayaCode: 16,
    ambassadorWilayaName: 'الجزائر العاصمة',
    ambassadorAvatar: '🌟',
    ambassadors: [
      {
        id: 'amb-1',
        name: 'علاء الدين (Alaa Eddine)',
        wilayaCode: 16,
        wilayaName: 'الجزائر العاصمة',
        institution: 'جامعة العلوم والتكنولوجيا USTHB باب الزوار',
        roleTitle: 'سفير وممثل كلية الإعلام الآلي والرياضيات',
        avatar: '🌟',
      },
      {
        id: 'amb-2',
        name: 'سامي بوزيد (Sami Bouzid)',
        wilayaCode: 31,
        wilayaName: 'وهران',
        institution: 'جامعة العلوم والتكنولوجيا وهران (USTO)',
        roleTitle: 'منسق طلبة الجذع المشترك MI',
        avatar: '👨‍💼',
      },
    ],
    attendees: SAMPLE_LMD_ATTENDEES,
    enrolledStudentsCount: 140,
    joinedStudentsCount: 128,
    replayViewsCount: 260,
    questionsCount: 31,
    meetUrl: '/room/room-lmd-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'Support: Espaces Vectoriels & Matrices.pdf',
  },
  {
    id: 'sess-9',
    roomId: 'room-lmd-kadri',
    moduleId: 'mod-lmd-analyse',
    moduleName: 'التحليل الرياضي والجبر الخطي (LMD MI L1)',
    courseTitle: 'حزمة مراجعة السنة الأولى جامعي (LMD CS & Math)',
    sessionNumber: 2,
    title: '02. المعادلات التفاضلية من الرتبة الثانية وتطبيقاتها في الفيزياء والنمذجة',
    date: '2026-08-25',
    timeSlot: '20:00 - 21:30',
    durationMinutes: 90,
    ambassadorId: 'amb-4',
    ambassadorName: 'فريد خليفي (Farid Khelifi)',
    ambassadorWilayaCode: 19,
    ambassadorWilayaName: 'سطيف',
    ambassadorAvatar: '👨‍🎓',
    ambassadors: [
      {
        id: 'amb-4',
        name: 'فريد خليفي (Farid Khelifi)',
        wilayaCode: 19,
        wilayaName: 'سطيف',
        institution: 'جامعة سطيف 1',
        roleTitle: 'مشرف الجلسة',
        avatar: '👨‍🎓',
      },
    ],
    attendees: SAMPLE_LMD_ATTENDEES,
    enrolledStudentsCount: 140,
    joinedStudentsCount: 132,
    replayViewsCount: 190,
    questionsCount: 26,
    meetUrl: '/room/room-lmd-kadri',
    status: 'COMPLETED',
    handoutPdfUrl: '/exams/samples/bac_math_serie1_2026.pdf',
    handoutTitle: 'Support: Equations Differentielles Ordre 2.pdf',
  }
];

// Helper functions for dynamic language selection
export function getLocalizedItemName(
  item: { nameAr: string; nameFr: string; nameEn?: string },
  locale: Locale
): string {
  if (locale === 'fr') return item.nameFr || item.nameAr;
  if (locale === 'en') return item.nameEn || item.nameFr || item.nameAr;
  return item.nameAr;
}

export function getLocalizedWilayaName(wilaya: Wilaya, locale: Locale): string {
  if (locale === 'fr') return wilaya.nameFr;
  if (locale === 'en') return wilaya.nameEn;
  return wilaya.nameAr;
}

export function getLocalizedAmbassadorBio(amb: AmbassadorProfile, locale: Locale): string {
  if (locale === 'fr') return amb.bioFr || amb.bioAr || '';
  if (locale === 'en') return amb.bioFr || amb.bioAr || '';
  return amb.bioAr || amb.bioFr || '';
}

